export const BASE_HOST = "https://web.cyberbells.com/DitroInfotech/Projects/flock/";
export const BASE_URL = `${BASE_HOST}api/`;
export const BASE_IMG_URL = `${BASE_HOST}assets/images/users/`;

export default (
  Server = {

    serverURL: `${BASE_URL}`,
    imgURL: `${BASE_IMG_URL}`,
    usersignup: `${BASE_URL}usersignup`,
    verify_user: `${BASE_URL}verify_user`,
    verify_email: `${BASE_URL}verify_email`,
    loginuser: `${BASE_URL}loginuser`,
    forgotpassword: `${BASE_URL}forgotPassword`,
    home: `${BASE_URL}home`,
    hot_boost: `${BASE_URL}filter_hot_boost`,
    venuedata_bytype: `${BASE_URL}venuedata_bytype`,
    mark_favourite_venue: `${BASE_URL}mark_favourite_venue`,
    venue_favourite_list: `${BASE_URL}venue_favourite_list`,
    venue_list_by_category: `${BASE_URL}venue_list_by_category`,
    searchvenue: `${BASE_URL}searchvenue`,
    faq: `${BASE_URL}faq`,
    single_venue_detail: `${BASE_URL}single_venue_detail`,
    checkin: `${BASE_URL}checkin`,
    dashboard: `${BASE_URL}dashboard`,
    featherdashboard: `${BASE_URL}feather_dashboard`,
    notifications: `${BASE_URL}notifications`,
    categorywise_booking: `${BASE_URL}categorywise_booking`,
    all_transaction: `${BASE_URL}all_transaction`,
    nearby_search: `${BASE_URL}nearby_search`,
    change_password: `${BASE_URL}change_password`,
    report_type: `${BASE_URL}report_type`,
    venue_reportt: `${BASE_URL}venue_reportt`,
    tutorials: `${BASE_URL}tutorials`,
    spoton: `${BASE_URL}spoton`,
    spoton_list: `${BASE_URL}spoton_list`,
    myprofile: `${BASE_URL}myprofile`,
    verify_mobile_status: `${BASE_URL}verify_mobile_status`,
    verify_email_status: `${BASE_URL}verify_email_status`,
    userdetails: `${BASE_URL}userdetails`,
    buy_coupon_list: `${BASE_URL}buy_coupon_list`,
    buy_coupon: `${BASE_URL}buy_coupon`,
    add_favouriteoffer: `${BASE_URL}add_favouriteoffer`,
    favourite_offerlist: `${BASE_URL}favourite_offerlist`,
    verified_redeem_code: `${BASE_URL}verified_redeem_code`,
    logout: `${BASE_URL}logout`,
    get_hours_by_venue: `${BASE_URL}get_hours_by_venue`,
    delete_account: `${BASE_URL}delete_account`,
    get_user_location: `${BASE_URL}get_user_location`,
    request_venue: `${BASE_URL}request_venue`,
    update_device_token: `${BASE_URL}update_device_token`,
    createAppLogs: `${BASE_URL}create_app_logs`,
  });
