export default {

    no_data: require("../assets/no_data.gif"),

    splash_logo: require("../assets/logo.png"),
    bird_logo: require("../assets/bird_logo.png"),
    splash_back: require("../assets/splash.png"),
    login_back: require("../assets/login_back.jpg"),
    google: require("../assets/google.png"),
    facebook: require("../assets/facebook.png"),
    apple: require("../assets/apple.png"),
    onBoard1: require("../assets/one_1.png"),
    onBoard2: require("../assets/two_1.png"),
    close: require("../assets/close.png"),
    onBoard3: require("../assets/two_2.png"),
    onBoard4: require("../assets/three_1.png"),
    onBoard5: require("../assets/three_2.png"),
    onBoard6: require("../assets/four_1.png"),
    done: require("../assets/done.png"),
    home: require("../assets/home.png"),
    fav: require("../assets/fav.png"),
    notify: require("../assets/notify.png"),
    profile: require("../assets/profile.png"),
    bird: require("../assets/bird.png"),
    bottomNav: require("../assets/bottom_nav.png"),
    sideNav: require("../assets/side_nav.png"),
    scanner: require("../assets/scanner.png"),
    qrscanner: require("../assets/qr_scanner.png"),
    hot: require("../assets/hot.png"),
    star: require("../assets/star.png"),
    nightlife: require("../assets/night_life.png"),
    food: require("../assets/food.png"),
    clubs: require("../assets/clubs.png"),
    entertainment: require("../assets/entertainment.png"),
    stays: require("../assets/stays.png"),
    banner1: require("../assets/banner1.png"),
    banner2: require("../assets/banner2.png"),
    banner3: require("../assets/banner3.png"),
    favHotel: require("../assets/fav_hotel.png"),
    favFood: require("../assets/fav_food.png"),
    favStore: require("../assets/fav_store.png"),
    favNight: require("../assets/fav_night.png"),
    favEnter: require("../assets/fav_enter.png"),
    hotelback1: require("../assets/hotelback1.png"),
    hotelback2: require("../assets/hotelback2.png"),
    remove: require("../assets/remove.png"),
    favourite: require("../assets/favourite.png"),
    ratingStar: require("../assets/rating_star.png"),
    back: require("../assets/back.png"),
    add: require("../assets/add.png"),
    businessEggs: require("../assets/business_eggs.png"),
    
    profileImg: require("../assets/profile_img.jpg"),
    sideArrow: require("../assets/side_arrow.png"),
    earned: require("../assets/earned.png"),
    spend: require("../assets/spend.png"),
    blackArrow: require("../assets/black_arrow.png"),
    navProfile: require("../assets/nav_profile.png"),
    navDashboard: require("../assets/nav_dashboard.png"),
    navFaq: require("../assets/nav_faq.png"),
    navReport: require("../assets/nav_report.png"),
    discount: require("../assets/discount.png"),
    navSetting: require("../assets/nav_setting.png"),
    navLogout: require("../assets/nav_logout.png"),
    points: require("../assets/points.png"),
    setting: require("../assets/setting.png"),
    whiteSideArrow: require("../assets/white_side_arrow.png"),
    sFood: require("../assets/s_food.png"),
    sStore: require("../assets/s_store.png"),

    sHotel: require("../assets/s_hotel.png"),
    sMovie: require("../assets/s_movie.png"),
    orangeHotel: require("../assets/orange_hotel.png"),
    orangeClub: require("../assets/orange_club.png"),
    orangeEntertain: require("../assets/orange_entertain.png"),
    search: require("../assets/search.png"),
    filter: require("../assets/filter.png"),
    nearby: require("../assets/nearby.png"),
    available: require("../assets/available.png"),
    menu: require("../assets/menu.png"),
    featherHotel: require("../assets/feather_hotel.png"),
    featherFood: require("../assets/feather_food.png"),
    featherNight: require("../assets/feather_night.png"),
    featherEntertain: require("../assets/feather_entertain.png"),
    settings: require("../assets/settings.png"),
    appTheme: require("../assets/app_theme.png"),

    tutorials: require("../assets/tutorials.png"),
    support: require("../assets/support.png"),
    tutorials1: require("../assets/tutorials1.png"),
    tutorials2: require("../assets/tutorials2.png"),
    dropDown: require("../assets/drop_down.png"),
    dropUp: require("../assets/drop_up.png"),
    background1: require("../assets/background1.png"),
    whiteBack: require("../assets/white_back.png"),
    blackBack: require("../assets/black_back.png"),
    whiteFav: require("../assets/white_fav.png"),
    blackFav: require("../assets/black_fav.png"),
    location: require("../assets/location.png"),
    locationPin: require("../assets/location_pin.png"),
    singleStar: require("../assets/single_star.png"),

    directionArrow: require("../assets/direction_arrow.png"),
    wifi: require("../assets/wifi.png"),
    food: require("../assets/food_single.png"),
    bar: require("../assets/bar.png"),
    pool: require("../assets/pool.png"),
    gaming: require("../assets/gaming.png"),
    map: require("../assets/map.png"),
    blueDropdown: require("../assets/blue_dropdown.png"),
    mapIcon: require("../assets/map_icon.png"),
    edit: require("../assets/edit.png"),
    greyFood: require("../assets/grey_food.png"),
    greyShop: require("../assets/grey_shop.png"),
    slider1: require("../assets/slider1.png"),
    slider2: require("../assets/slider2.png"),
    slider3: require("../assets/slider3.png"),
    eye: require("../assets/eye.png"),
    hide: require("../assets/hide.png"),

    one: require("../assets/onex.png"),
    two: require("../assets/twox.png"),
    three: require("../assets/threex.png"),
    four: require("../assets/fourx.png"),
    five: require("../assets/fivex.png"),

    people: require("../assets/people.png"),
    beer: require("../assets/beer.png"),
    offer1: require("../assets/offer1.png"),
    offer2: require("../assets/offer2.png"),
    offer3: require("../assets/offer3.png"),
    delete: require("../assets/delete.png"),

    checkbox: require("../assets/checkbox.png"),
    checkbox_fill: require("../assets/checkbox_fill.png"),

    AppOffer: require("../assets/app_offer.png"),
    VenueOffer: require("../assets/venue_offer.png"),
    FlockBird: require("../assets/flock_bird.png"),
    verifyBadge: require("../assets/verify.png"),

    ScanBackground: require("../images/scan_background.png"),
    sleepy_bk: require("../assets/sleepy.png"),
    sleepy: require("../assets/flockzzz.png"),

    play_button: require("../assets/play_button.png")
}