import { Image } from "react-native";

const assets = "../assets/";

export default {
    uri : (image: number) => Image.resolveAssetSource(image).uri,
    flock_marker: require(`${assets}flock_marker.png`),
    venue_marker: require(`${assets}venue_marker.png`),
    no_data: require(`${assets}no_data.gif`),
    splash_logo: require(`${assets}logo.png`),
    bird_logo: require(`${assets}bird_logo.png`),
    loader: require(`${assets}Bird_Full_Eye_Blinking.gif`),
    splash_back: require(`${assets}splash.png`),
    login_back: require(`${assets}login_back.jpg`),
    login_bg_darkmode: require(`${assets}login_bg_darkmode.jpeg`),
    home: require(`${assets}home.png`),
    fav: require(`${assets}fav.png`),
    notify: require(`${assets}notify.png`),
    profile: require(`${assets}profile.png`),
    bird: require(`${assets}bird.png`),
    venue_request: require(`${assets}request_venue.png`),
    bottomNav: require(`${assets}bottom_nav.png`),
    bottomBird: require(`${assets}bottom_bird.png`),
    sideNav: require(`${assets}side_nav.png`),
    scanner: require(`${assets}scanner.png`),
    bottomNavDark:require(`${assets}bottom_nav_dark.png`),
    qrscanner: require(`${assets}qr_scanner.png`),
    hot: require(`${assets}hot.png`),
    star: require(`${assets}star.png`),
    favourite: require(`${assets}favourite.png`),
    back: require(`${assets}back.png`),
    add: require(`${assets}add.png`),
    venueWhite: require(`${assets}white_venue.png`),
    profileImg: require(`${assets}profile_img.png`),
    sideArrow: require(`${assets}side_arrow.png`),
    earned: require(`${assets}earned.png`),
    spend: require(`${assets}spend.png`),
    blackArrow: require(`${assets}black_arrow.png`),
    navFaq: require(`${assets}nav_faq.png`),
    navReport: require(`${assets}nav_report.png`),
    discount: require(`${assets}discount.png`),
    navLogout: require(`${assets}nav_logout.png`),
    setting: require(`${assets}setting.png`),
    search: require(`${assets}search.png`),
    tutorials: require(`${assets}tutorials.png`),
    support: require(`${assets}support.png`),
    dropDown: require(`${assets}drop_down.png`),
    dropUp: require(`${assets}drop_up.png`),
    whiteBack: require(`${assets}white_back.png`),
    blackBack: require(`${assets}black_back.png`),
    location: require(`${assets}location.png`),
    directionArrow: require(`${assets}direction_arrow.png`),
    blueDropdown: require(`${assets}blue_dropdown.png`),
    one: require(`${assets}onex.png`),
    two: require(`${assets}twox.png`),
    three: require(`${assets}threex.png`),
    four: require(`${assets}fourx.png`),
    five: require(`${assets}fivex.png`),
    AppOffer: require(`${assets}app_offer.png`),
    VenueOffer: require(`${assets}venue_offer.png`),
    FlockBird: require(`${assets}flock_bird.png`),
    verifyBadge: require(`${assets}verify.png`),
    ScanBackground: require(`${assets}scan_background.png`),
    sleepy: require(`${assets}flockzzz.png`),
    play_button: require(`${assets}play_button.png`),
    success: require(`${assets}success.png`),
    birdapp: require(`${assets}birdapp.png`),
    buildingapp: require(`${assets}buildingapp.png`),
    placeholder: require(`${assets}placeholder.png`)
}